- name: Rollback Adamant node changes
  hosts: adamant_nodes
  become: true
  roles:
    - role: adamant_node
      tags: rollback

- name: Install and run Adamant node
  hosts: adamant_nodes
  become: true
  roles:
    - role: adamant_node
      tags: install
