# adamant_node/tasks/install.yml

- name: Copy Dockerfile to server
  copy:
    src: "{{ role_path }}/files/Dockerfile"
    dest: /tmp/Dockerfile
    mode: '0644'

- name: Build Docker image
  community.docker.docker_image:
    name: adamant:latest
    build:
      path: /tmp
      nocache: true
    source: build

- name: Create adamant app volume
  docker_volume:
    name: adamant_app
    state: present

- name: Create adamant postgres volume
  docker_volume:
    name: adamant_postgres
    state: present

- name: Download adamant snapshot
  docker_container:
    name: adamant_node
    image: adamant:latest
    command: wget https://explorer.adamant.im/db_backup.sql.gz -O db_backup.sql.gz
    volumes:
      - adamant_app:/app
      - adamant_postgres:/var/lib/postgresql/15/main
    detach: false
    tty: true

- name: Gunzip adamant snapshot
  docker_container:
    name: adamant_node
    image: adamant:latest
    command: gunzip db_backup.sql.gz
    volumes:
      - adamant_app:/app
      - adamant_postgres:/var/lib/postgresql/15/main
    detach: false
    tty: true

- name: Change mod adamant snapshot
  docker_container:
    name: adamant_node
    image: adamant:latest
    command: chmod 777 db_backup.sql
    volumes:
      - adamant_app:/app
      - adamant_postgres:/var/lib/postgresql/15/main
    detach: false
    tty: true

- name: Import adamant snapshot
  docker_container:
    name: adamant_node
    image: adamant:latest
    command: bash -c 'service postgresql start && su - adamant -c "psql -U adamant -d adamant_main -f /app/db_backup.sql" && service postgresql stop && rm /app/db_backup.sql'
    volumes:
      - adamant_app:/app
      - adamant_postgres:/var/lib/postgresql/15/main
    detach: false

- name: Run Adamant container
  community.docker.docker_container:
    name: adamant_node
    image: adamant:latest
    state: started
    restart_policy: always
    volumes:
      - adamant_app:/app
      - adamant_postgres:/var/lib/postgresql/15/main
    ports:
      - 36666:36666
      - 36668:36668
  tags:
    - rerun_adamant

- name: Remove Dockerfile from server
  file:
    path: /tmp/Dockerfile
    state: absent


- name: Remove container
  community.docker.docker_container:
    name: adamant_node
    image: adamant:latest
    state: stopped
  notify:
    - Remove adamant_node container
  tags:
    - never
    - reset_adamant
